String params = "["
  "{"
  "'name':'sda',"
  "'label':'I2C-SDA',"
  "'type':"+String(INPUTNUMBER)+","
  "'min':4,'max':34,"
  "'default':'14'"
  "},"
  "{"
  "'name':'scl',"
  "'label':'I2C-SCL',"
  "'type':"+String(INPUTNUMBER)+","
  "'min':4,'max':34,"
  "'default':'15'"
  "},"
  "{"
  "'name':'mqtt-address',"
  "'label':'MQTT IP ADDRESS',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'192.168.1.130'"
  "},"
  "{"
  "'name':'mqtt-username',"
  "'label':'MQTT User Name',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'esp'"
  "}," 
  "{"
  "'name':'mqtt-pw',"
  "'label':'MQTT Password',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'doodlehead'"
  "},"
  "{"
  "'name':'mqtt-topic',"
  "'label':'MQTT Topic',"
  "'type':"+String(INPUTTEXT)+","
  "'default':''"
  "}," 
  "{"
  "'name':'mqtt-port',"
  "'label':'MQTT Port',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'1883'"
  "}," 
  "{"
  "'name':'switch020',"
  "'label':'MCP23017 at 0x20',"
  "'type':"+String(INPUTCHECKBOX)+","
  "'default':'1'"
  "},"
  "{"
  "'name':'switch021',"
  "'label':'MCP23017 at 0x21',"
  "'type':"+String(INPUTCHECKBOX)+","
  "'default':'1'"
  "},"
  "{"
  "'name':'displays',"
  "'label':'Connected Displays',"
  "'type':"+String(INPUTMULTICHECK)+","
  "'options':["
  "{'v':'0','l':'0.96 I2C'},"
  "{'v':'1','l':'240x240 SPI'},"
  "{'v':'2','l':'SPI'},"
  "{'v':'3','l':'I2C'}],"
  "'default':''"
  "}"
  "]";
