String params = "["
  "{"
  "'name':'ssid',"
  "'label':'Name of WLAN',"
  "'type':"+String(INPUTTEXT)+","
  "'default':''"
  "},"
  "{"
  "'name':'pwd',"
  "'label':'WLAN Password',"
  "'type':"+String(INPUTPASSWORD)+","
  "'default':''"
  "},"
  "{"
  "'name':'sda',"
  "'label':'I2C-SDA',"
  "'type':"+String(INPUTNUMBER)+","
  "'min':4,'max':34,"
  "'default':'14'"
  "},"
  "{"
  "'name':'scl',"
  "'label':'I2C-SCL',"
  "'type':"+String(INPUTNUMBER)+","
  "'min':4,'max':34,"
  "'default':'15'"
  "},"
  "{"
  "'name':'mqtt-address',"
  "'label':'MQTT IP ADDRESS',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'192.168.1.130'"
  "},"
  "{"
  "'name':'mqtt-username',"
  "'label':'MQTT User Name',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'test'"
  "}," 
  "{"
  "'name':'mqtt-pw',"
  "'label':'MQTT Password',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'password'"
  "},"
  "{"
  "'name':'mqtt-topic',"
  "'label':'MQTT Topic',"
  "'type':"+String(INPUTTEXT)+","
  "'default':''"
  "}," 
  "{"
  "'name':'mqtt-port',"
  "'label':'MQTT Port',"
  "'type':"+String(INPUTTEXT)+","
  "'default':'1883'"
  "}," 
  "{"
  "'name':'mqtt-ad',"
  "'label':'MQTT Auto Discovery',"
  "'type':"+String(INPUTCHECKBOX)+","
  "'default':'0'"
  "},"
  "{"
  "'name':'spi-tft',"
  "'label':'SPI TFT ST7789 Connected',"
  "'type':"+String(INPUTCHECKBOX)+","
  "'default':'1'"
  "},"
  "{"
  "'name':'tft-rotation',"
  "'label':'TFT Position (0-3)',"
  "'type':"+String(INPUTNUMBER)+","
  "'min':0,'max':3,"
  "'default':'1'"
  "}"
  "]";

const char* OTAserverIndex =
"<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>"
"</head>"
"<h1 style='text-align: center; font-family: Helvetica;'>Firmware Update</h1>"
"<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
   "<input type='file' name='update'>"
        "<input type='submit' value='Update'>"
    "</form>"
 "<div id='prg'>progress: 0%</div>"
 "<script>"
  "$('form').submit(function(e){"
  "e.preventDefault();"
  "var form = $('#upload_form')[0];"
  "var data = new FormData(form);"
  " $.ajax({"
  "url: '/update',"
  "type: 'POST',"
  "data: data,"
  "contentType: false,"
  "processData:false,"
  "xhr: function() {"
  "var xhr = new window.XMLHttpRequest();"
  "xhr.upload.addEventListener('progress', function(evt) {"
  "if (evt.lengthComputable) {"
  "var per = evt.loaded / evt.total;"
  "$('#prg').html('progress: ' + Math.round(per*100) + '%');"
  "}"
  "}, false);"
  "return xhr;"
  "},"
  "success:function(d, s) {"
  "console.log('success!')"
 "},"
 "error: function (a, b, c) {"
 "}"
 "});"
 "});"
 "</script>";
